name: Update Documentation

# Temporarily disabled - re-enable after fixing broken links
on:
  workflow_dispatch: # Manual trigger only

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        
    - name: Validate Docker commands in docs
      run: |
        # Extract and validate Docker commands from markdown files
        grep -h "docker run" *.md || echo "No docker commands found"
        grep -h "ghcr.io" *.md || echo "No container registry references found"
